repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ".*\\.md"
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ruff
        name: Check python (ruff)
        language: system
        types_or: [python, pyi]
        require_serial: true
        entry: pdm run ruff check --force-exclude
        args:
          [--output-format=full, --fix, --show-fixes, --exit-non-zero-on-fix]
      - id: ruff-format
        name: Format python (ruff)
        language: system
        types_or: [python, pyi]
        require_serial: true
        entry: pdm run ruff format --force-exclude
      - id: nixfmt
        name: Format Nix (nixfmt)
        types: [nix]
        language: system
        require_serial: true
        entry: bash -c 'command -v nix && nix "$@" || echo "skipping nixfmt"' nix
        args:
          - --experimental-features
          - nix-command flakes
          - --accept-flake-config
          - fmt

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:
      - id: check-github-actions
        name: Check Github actions
      - id: check-github-workflows
        name: Check Github workflows
