class AccessFS:
    @staticmethod
    def read(dir: str) -> "AccessFS": ...
    @staticmethod
    def read_write(dir: str) -> "AccessFS": ...
    @staticmethod
    def make_reg(dir: str) -> "AccessFS": ...
    @staticmethod
    def make_dir(dir: str) -> "AccessFS": ...

def restrict_access(*args: AccessFS) -> None: ...
